project:
  type: book

book:
  title: "HNU2000-A25"
  subtitle: "Humanités Numériques : technologies"
  author: "[Mathilde Verstraete](mailto:mathilde.verstraete@umontreal.ca)"
  date: "[Automne] 2025"
  date-format: "[Automne] YYYY"
  search: true
  page-navigation: true
  downloads: pdf 
  sidebar: 
    style: docked 
    background: light 
  page-footer: "HNU2000-A25, Mathilde Verstraete"
  chapters:
    - index.qmd
    - calendrier.qmd
    - 01a.qmd
    - 01b.qmd 
    - 02.qmd
    - 03.qmd 
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 09.qmd
    - 11.qmd
    - references.qmd

lang: fr-FR

bibliography: ref.bib
csl: apa.csl

language: 
  title-block-author-single: "Chargée de cours" 
  toc-title-document: "Contenu" 
  title-block-published: "Session"

comments:
  hypothesis: true

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: minty 
      dark: superhero
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    mainfont: EB Garamond  
    link-citations: true
    toc: false
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{} 
        \fancyfoot[C]{\thepage}
        \fancyhead[L]{HNU2000-A25} 
        \fancyhead[R]{\leftmark}
        \renewcommand{\chaptermark}[1]{\markboth{#1}{}}
    include-after-body: 
      text: | 
        \tableofcontents